socialnetwork/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.globalstream_action, name='home'),
    path('login', views.login_action, name='login'),
    path('logout', views.logout_action, name='logout'),
    path('register', views.register_action, name='register'),
    path('globalstream', views.globalstream_action, name='globalstream'),
    path('add_post', views.add_post, name='add_post'),
    path('profile/<int:id>', views.profile_action, name='profile'),
    path('follow/<int:id>', views.follow_action, name='follow'),
    path('get_photo/<int:id>', views.get_photo, name='get_photo'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('followerstream', views.followerstream, name='followerstream'),

    path('add-comment', views.add_comment),
    path('refresh-global', views.refresh_global),
    path('refresh-follower', views.refresh_follower),
]

webapps/urls.py
from django.urls import path, include
from socialnetwork import views

urlpatterns = [
    path('', views.login_action),
    path('socialnetwork/', include('socialnetwork.urls')),
]

socialnetwork/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    content       = models.CharField(max_length=300)
    post_creator    = models.ForeignKey(User, related_name="post_creators", on_delete=models.CASCADE)
    post_time = models.DateTimeField()
    def __str__(self):
    	return 'id=' + str(self.id) 


class Profile(models.Model):
	picture = models.FileField(blank=True)
	pic_saved = models.FileField(blank=True)
	user_bio     = models.CharField(max_length=200)
	content_type = models.CharField(max_length=50)
	user = models.ForeignKey(User,default=None, null=True,on_delete=models.PROTECT, related_name="profile_creators")
	followlist = models.ManyToManyField(User, related_name='follow', symmetrical=False)
	def __str__(self):
		return 'id=' + str(self.id)

class Comment(models.Model):
    content       = models.CharField(max_length=300)
    comment_creator    = models.ForeignKey(User, related_name="comment_creators", on_delete=models.CASCADE)
    comment_time = models.DateTimeField()
    post_id = models.CharField(max_length=100)
    creator_id=models.CharField(max_length=100)

    def __str__(self):
    	return 'id=' + str(self.id)

socialnetwork/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from socialnetwork.models import *

MAX_UPLOAD_SIZE = 2500000

class LoginForm(forms.Form):
    username = forms.CharField(max_length = 20, widget = forms.TextInput(attrs={'id':'id_username'}))
    password = forms.CharField(max_length = 200, widget = forms.PasswordInput(attrs={'id':'id_password'}))

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            error = forms.ValidationError("Invalid username/password")
            raise error


        # We must return the cleaned data we got from our parent.
        return cleaned_data

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=20,  widget = forms.TextInput(attrs={'id':'id_username'}))
    password1  = forms.CharField(max_length = 200, 
                                 label='Password', 
                                 widget = forms.PasswordInput(attrs={'id':'id_password'}))
    password2  = forms.CharField(max_length = 200, 
                                 label='Confirm',  
                                 widget = forms.PasswordInput(attrs={'id':'id_confirm_password'}))
    
    email      = forms.CharField(max_length=50,
                                 widget = forms.EmailInput(attrs={'id':'id_email'}))
    first_name   = forms.CharField(max_length = 20,widget = forms.TextInput(attrs={'id':'id_first_name'}))
    last_name  = forms.CharField(max_length=20,widget = forms.TextInput(attrs={'id':'id_last_name'}))
    


    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super(RegistrationForm, self).clean()

        # Confirms that the two password fields match
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")

        # We must return the cleaned data we got from our parent.
        return cleaned_data

    # Customizes form validation for the username field.
    def clean_username(self):
        # Confirms that the username is not already present in the
        # User model database.
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__exact=username):
            raise forms.ValidationError("Username is already taken.")

        # We must return the cleaned data we got from the cleaned_data
        # dictionary
        return username
   

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('picture', )

    def clean_picture(self):
        picture = self.cleaned_data['picture']
        if not picture:
            raise forms.ValidationError('You must upload a picture')
        if not picture.content_type or not picture.content_type.startswith('image'):
            raise forms.ValidationError('File type is not image')
        if picture.size > MAX_UPLOAD_SIZE:
            raise forms.ValidationError('File too big (max size is {0} bytes)'.format(MAX_UPLOAD_SIZE))
        return picture

socialnetwork/views.py
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse, Http404

from django.shortcuts import render, redirect,get_object_or_404
from django.urls import reverse
from django.core import serializers

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.utils.dateparse import parse_datetime
from django.views.decorators.csrf import ensure_csrf_cookie

from django.utils import timezone

from socialnetwork.forms import *
from socialnetwork.models import *

def login_action(request):
    context = {}

    # Just display the registration form if this is a GET request.
    if request.method == 'GET':
        context['form'] = LoginForm()
        return render(request, 'socialnetwork/login.html', context)

    # Creates a bound form from the request POST parameters and makes the 
    # form available in the request context dictionary.
    form = LoginForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'socialnetwork/login.html', context)

    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

    login(request, new_user)
    return redirect(reverse('home'))

def logout_action(request):
    logout(request)
    return redirect(reverse('login'))

def register_action(request):
    context = {}

    # Just display the registration form if this is a GET request.
    if request.method == 'GET':
        context['form'] = RegistrationForm()
        return render(request, 'socialnetwork/register.html', context)

    # Creates a bound form from the request POST parameters and makes the 
    # form available in the request context dictionary.
    form = RegistrationForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'socialnetwork/register.html', context)

    # At this point, the form data is valid.  Register and login the user.
    new_user = User.objects.create_user(username=form.cleaned_data['username'], 
                                        password=form.cleaned_data['password1'],
                                        email=form.cleaned_data['email'],
                                        first_name=form.cleaned_data['first_name'],
                                        last_name=form.cleaned_data['last_name'])
    new_user.save()
    new_profile=Profile(user=new_user)
    new_profile.save()

    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password1'])

    login(request, new_user)
    return redirect(reverse('home'))

@ensure_csrf_cookie
@login_required
def globalstream_action(request):
    posts = Post.objects.all().order_by('-post_time')
    context={'posts': posts}
    return render(request, 'socialnetwork/globalstream.html', context)

@login_required
def profile_action(request, id):
    if id == request.user.id:
        context={}
        profile=Profile.objects.filter(id=id).last()
        context['form'] = ProfileForm()
        context['profile'] = profile
        if len(str(profile.user_bio).strip())==0 or profile.user_bio is None:
            context['user_bio'] = 'Default blah blah blah.'
        else:
            context['user_bio'] = '{0}'.format(profile.user_bio)
        context['followlist']=profile.followlist.all()
        return render(request, 'socialnetwork/profile.html', context)
    else:
        context={}
        other_user=User.objects.get(id=id)
        profile=Profile.objects.filter(id=id).last()
        context['form'] = ProfileForm()
        context['profile'] = profile
        if len(str(profile.user_bio).strip())==0 or profile.user_bio is None:
            context['user_bio'] = 'Default blah blah blah.'
        else:
            context['user_bio'] = '{0}'.format(profile.user_bio)
        myProfile = Profile.objects.filter(id=request.user.id).last()
        if other_user in myProfile.followlist.all():
            context['follow'] = 'unfollow'
        else:
            context['follow'] = 'follow'
        return render(request, 'socialnetwork/other_profile.html', context) 

@login_required
def follow_action(request, id):
    context = {}
    other_profile = User.objects.get(id=id)
    profile = Profile.objects.filter(id=id).last()
    context['form'] = ProfileForm()
    context['profile'] = profile
    if len(str(profile.user_bio).strip())==0 or profile.user_bio is None:
        context['user_bio'] = 'Default blah blah blah.'
    else:
        context['user_bio'] = '{0}'.format(profile.user_bio)
    myProfile = Profile.objects.filter(id=request.user.id).last()
    if other_profile in myProfile.followlist.all():
        myProfile.followlist.remove(other_profile)
        context['follow'] = 'follow'
    else:
        myProfile.followlist.add(other_profile)
        context['follow'] = 'unfollow'
    myProfile.save()
    return render(request, 'socialnetwork/other_profile.html', context)


@login_required
def add_post(request):
    if request.method=='GET':
        posts = Post.objects.all().order_by('-post_time')
        context={'posts': posts}
        return render(request, 'socialnetwork/globalstream.html',context)
    elif request.method =='POST':
        context = {}
        error=[]

        if request.POST.get('post_text') =="":
            error.append("you must enter something")
        else:
            new_post = Post(content=request.POST.get('post_text'),
                            post_creator=request.user,
                            post_time = timezone.now())
            new_post.save()

        posts = Post.objects.all().order_by('-post_time')

        context={'posts': posts,'errors':error}
        return render(request, 'socialnetwork/globalstream.html',context)


@login_required
def followerstream(request):
    myProfile = Profile.objects.filter(id=request.user.id).last()
    posts = Post.objects.filter(post_creator__in = myProfile.followlist.all()).order_by('-post_time')
    context={'posts': posts}
    return render(request, 'socialnetwork/followerstream.html',context)

@login_required
def update_profile(request):
    context = {}
    profile=Profile.objects.filter(id=request.user.id).last()
    form = ProfileForm(request.POST, request.FILES, instance=profile)
    if not form.is_valid():
        context['form'] = form
    else:
        pic = form.cleaned_data['picture']
        print('Uploaded picture: {} (type={})'.format(pic, type(pic)))
        profile.user_bio = request.POST.get('user_bio')
        profile.content_type = form.cleaned_data['picture'].content_type
        profile.pic_saved=profile.picture
        profile.save()
        profile.picture=None
        profile.save()
        form.save()
        context['form'] = ProfileForm()
    context['profile'] = profile
    if len(str(profile.user_bio).strip())==0 or profile.user_bio is None:
        context['user_bio'] = 'Default blah blah blah.'
    else:
        context['user_bio'] = '{0}'.format(profile.user_bio)

    context['followlist'] = profile.followlist.all()
    return render(request, 'socialnetwork/profile.html', context)

@login_required
def get_photo(request, id):
    profile = get_object_or_404(Profile, id=id)
    # Maybe we don't need this check as form validation requires a picture be uploaded.
    # But someone could have delete the picture leaving the DB with a bad references.
    if not profile.pic_saved:
        raise Http404

    return HttpResponse(profile.pic_saved, content_type=profile.content_type)

@login_required
def add_comment(request):
    if request.method != 'POST':
        raise Http404

    if not 'comment_text' in request.POST or not request.POST['comment_text']:
        message = 'You must enter an comment to add.'
        json_error = '{ "error": "'+message+'" }'
        return HttpResponse(json_error, content_type='application/json')
    new_comment = Comment(content=request.POST['comment_text'],
                    comment_creator = request.user,
                    comment_time = timezone.now(),
                    creator_id=request.user.id,
                    post_id = request.POST['id'])
    new_comment.save()
    response_text = serializers.serialize('json', [Comment.objects.last()])
    return HttpResponse(response_text, content_type='application/json')


def refresh_global(request):
    last_refresh = parse_datetime(request.GET['last_refresh'])
    print(last_refresh)
    print(request.user.username)
    response_text1=serializers.serialize('json',Post.objects.filter(post_time__gt=last_refresh))
    response_text2 = serializers.serialize('json',Comment.objects.filter(comment_time__gt=last_refresh))
    print(Post.objects.filter(post_time__gt=last_refresh).count())
    print(Comment.objects.filter(comment_time__gt=last_refresh).count())
    if Post.objects.filter(post_time__gte=last_refresh).count()==Post.objects.all().count():
        response_text= response_text2
    elif Post.objects.filter(post_time__gte=last_refresh).count()>0 and Comment.objects.filter(comment_time__gte=last_refresh).count()==0:
        response_text= response_text1
    elif Post.objects.filter(post_time__gte=last_refresh).count()>0:
        response_text=response_text1[:len(response_text1)-1]+','+response_text2[1:]
    else:
        response_text= response_text2
    print(response_text)
    return HttpResponse(response_text, content_type='application/json')

def refresh_follower(request):
    myProfile = Profile.objects.filter(id=request.user.id).last()
    last_refresh = parse_datetime(request.GET['last_refresh'])
    print(last_refresh)
    posts = Post.objects.filter(post_creator__in = myProfile.followlist.all()).order_by('-post_time')

socialnetwork/templates/socialnetwork/base.html
<!doctype html>
<html>
	<head>
	    <meta charset="utf-8">
	    {% load staticfiles %}
		<link href="{% static 'socialnetwork/base.css' %}" rel="stylesheet" type="text/css">
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
            crossorigin="anonymous"></script>
        <script src="{% static 'socialnetwork/todo.js' %}" type="text/javascript"></script>
		<title> {% block title %} SocialBook {% endblock %} </title>
	</head>

	<body>
		<div class= "head-container">
			<div class="big-heading" id="id_name_of_site">
				Blog Master
			</div>

			<div class="user-info">
				{% block user-info %}
				{% endblock %}
		    </div>
		</div>

	    <div class="content">
		    {% block content %}
		    {% endblock %}
		</div>
	</body>
</html>

socialnetwork/templates/socialnetwork/followerstream.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
<div class="dropdown">
  <a class="dropdownmain" id ="id_logged_in_user_name">  {{user.first_name}} {{user.last_name}}</a>
  <div class="dropdown-content">
    <a href="{% url 'globalstream' %}" id ="id_nav_global_stream">Global Stream</a>
    <a href="{% url 'followerstream' %}" id ="id_nav_follower_stream">Follower Stream</a>
    <a href="{% url 'profile' user.id %}" id ="id_nav_profile">My Profile</a>
    <a href="{% url 'login' %}" id ="id_nav_logout">Logout</a>
</div>
</div>
{% endblock %}

{% block content %}
<p>Follower Stream</p>
{% for error in errors %}
    <div class="error" id="global_error">
        {{error}}
    </div>
{% endfor %}

<newpost></newpost>
{% for post in posts %}
    <a href="{% url 'profile' post.post_creator.id %}" id="id_post_profile_{{post.id}}">Posted by {{post.post_creator}}</a>
    <span id="id_post_text_{{post.id}}" >{{post.content}}</span>
    <span id = "id_post_date_time_{{post.id}}">{{post.post_time}}</span>
    <ol id="todo-list_{{post.id}}">
    </ol>
    <label>Comment:</label>
    <input id="comment_{{post.id}}" type="text" name="comment">
    <button onclick="addComment({{post.id}})">Comment</button>
    <span id="error" class="error"></span>

{% endfor %}
<hidden></hidden>

{% endblock %}

socialnetwork/templates/socialnetwork/globalstream.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
<div class="dropdown">
  <a class="dropdownmain" id ="id_logged_in_user_name">  {{user.first_name}} {{user.last_name}}</a>
  <div class="dropdown-content">
    <a href="{% url 'globalstream' %}" id ="id_nav_global_stream">Global Stream</a>
    <a href="{% url 'followerstream' %}" id ="id_nav_follower_stream">Follower Stream</a>
    <a href="{% url 'profile' user.id %}" id ="id_nav_profile">My Profile</a>
    <a href="{% url 'login' %}" id ="id_nav_logout">Logout</a>
</div>
</div>
{% endblock %}

{% block content %}

<p>Global Stream</p>
{% for error in errors %}
    <div class="error" id="global_error">
        {{error}}
    </div>
{% endfor %}
<form method="post" action="{% url 'add_post' %}">
    New Post:
    <input type="text" name="post_text" id="id_post_text">
    <button type="submit" id="id_post_button">Submit</button><br>
    {% csrf_token %}
</form>

<newpost></newpost>
{% for post in posts %}
    <a href="{% url 'profile' post.post_creator.id %}" id="id_post_profile_{{post.id}}">Posted by {{post.post_creator}}</a>
    <span id="id_post_text_{{post.id}}" >{{post.content}}</span>
    <span id = "id_post_date_time_{{post.id}}">{{post.post_time}}</span>
    <ol id="todo-list_{{post.id}}">
    </ol>
    <label>Comment:</label>
    <input id="comment_{{post.id}}" type="text" name="comment">
    <button onclick="addComment({{post.id}})">Comment</button>
    <span id="error" class="error"></span><br>
{% endfor %}
{% endblock %}

socialnetwork/templates/socialnetwork/login.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div>
        <a href="{% url 'register' %}" id="id_register_link" class="dropdownmain">Register</a>
    </div>
{% endblock %}


{% block content %}
    <p>Login</p>

    <form method="post" action="{% url 'login' %}">
        <table class="logintable">
            {{form}}
        </table>
        {% csrf_token %}
        <button type="submit" id="id_login_button">Submit</button>
    </form>

{% endblock %}

socialnetwork/templates/socialnetwork/other_profile.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
<div class="dropdown">
  <a class="dropdownmain" id ="id_logged_in_user_name">
  {{user.first_name}} {{user.last_name}}</a>
    <div class="dropdown-content">
        <a href="{% url 'globalstream' %}" id ="id_nav_global_stream">Global Stream</a>
        <a href="{% url 'followerstream' %}" id ="id_nav_follower_stream">Follower Stream</a>
        <a href="{% url 'profile' user.id %}" id ="id_nav_profile">My Profile</a>
        <a href="{% url 'login' %}" id ="id_nav_logout">Logout</a>
    </div>
</div>
{% endblock %}


{% block content %}
<span id="id_user_name">Profile Page for {{profile.user.first_name}} {{profile.user.last_name}}</span>

<div>
    {% if profile.pic_saved %}
        <img src="{% url 'get_photo' profile.id %}" id="id_user_picture" width="200px">
        <br>
    {% else %}
        <img src="https://i.stack.imgur.com/l60Hf.png" id="id_user_picture" width="200px">
        <br>
    {% endif %}
</div>
<textarea type="text" name="user_bio" rows="10" cols="100" readonly="" id="id_user_bio">{{user_bio}}</textarea><br>

<form action="{% url 'follow' profile.user.id %}" method="post" class="profile-form">
    <button type="submit" id="{{follow}}">{{follow}}</button>
    {% csrf_token %}
</form>

{% endblock %}

socialnetwork/templates/socialnetwork/profile.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
<div class="dropdown">
  <a class="dropdownmain" id ="id_logged_in_user_name">
  {{user.first_name}} {{user.last_name}}</a>
    <div class="dropdown-content">
        <a href="{% url 'globalstream' %}" id ="id_nav_global_stream">Global Stream</a>
        <a href="{% url 'followerstream' %}" id ="id_nav_follower_stream">Follower Stream</a>
        <a href="{% url 'profile' user.id %}" id ="id_nav_profile">My Profile</a>
        <a href="{% url 'login' %}" id ="id_nav_logout">Logout</a>
    </div>
</div>
{% endblock %}


{% block content %}
<span id="id_user_name">Profile Page for {{user.first_name}} {{user.last_name}}</span>

<div>
    {% if profile.pic_saved %}
        <img src="{% url 'get_photo' profile.id %}"  id="id_user_picture" width="200px">
        <br>
    {% else %}
        <img src="https://i.stack.imgur.com/l60Hf.png" id="id_user_picture" width="200px">
        <br>
    {% endif %}
</div>
<form enctype="multipart/form-data" action="{% url 'update_profile'%}" method="post" class="profile-form">
    <table>
        <tr>
            <td>{{form.label_tag}}</td>
            <td>{{form}}</td>
            <td class="error">
                {% for error in field.errors %} {{error}} {% endfor %}
            </td>
        </tr>
    </table>
    <textarea type="text" name="user_bio" id="id_bio_text" rows="10" cols="100">{{user_bio}}</textarea><br>
    <button type="submit" id="id_update_profile_button">Submit</button><br>
    {% csrf_token %}
</form>
You are following:<br>
{% for followPerson in followlist %}
    <a href="{% url 'profile' followPerson.id %}" id="id_profile_link_{{followPerson.first_name}}_{{followPerson.last_name}}">{{followPerson.first_name}} {{followPerson.last_name}}</a><br>
{% endfor %}

{% endblock %}

socialnetwork/templates/socialnetwork/register.html
{% extends "socialnetwork/base.html" %}


{% block user-info %}
    <div>
        <a href="{% url 'login' %}" id="id_login_link">Login</a>
    </div>
{% endblock %}


{% block content %}
    <p>Register</p>

    <form method="post" action="{% url 'register' %}">
        <table class="registertable">
            {% for field in form.visible_fields %}
                <tr>
                    <td>{{field.label_tag}}</td>
                    <td>{{field}}</td>
                    <td class="error">
                        {% for error in field.errors %} {{error}} {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% csrf_token %}
        <button type="submit" id="id_register_button">Submit</button>
    </form>

    {% for error in form.non_field_errors %}
        <p class="error">
            {{ error }}
        </p>
    {% endfor %}

{% endblock %}